define(function(){
    var $self = {
        MAIN_CIRCLE_LOOP_START:"MAIN_CIRCLE_LOOP_START",
        MAIN_CIRCLE_LOOP_STOP:"MAIN_CIRCLE_LOOP_STOP",
        MAIN_GO_PAGE_MOVE:"MAIN_GO_PAGE_MOVE",
        MAIN_ACTIVE_MENU:"MAIN_ACTIVE_MENU",
        MAIN_CIRCLE_SCALE_CHANGE:"MAIN_CIRCLE_SCALE_CHANGE",
        MAIN_MOTION_START:"MAIN_MOTION_START",
        MAIN_MOTION_STOP:"MAIN_MOTION_STOP",

        MAIN_TOUCH_SWIPE:"MAIN_TOUCH_SWIPE"
    }

    return $self;
})